1

SELECT [EMPL_NUM], [Name], [Age], [TITLE]
FROM [dbo].[SALESREPS]
WHERE Age > 45
ORDER BY Age DESC;


2  

SELECT DISTINCT [MFR], [PRODUCT]
FROM [dbo].[ORDERS]
WHERE YEAR([ORDER_DATE]) = 2008;

3


SELECT TOP 1 WITH TIES [REP], COUNT(*) AS TotalOrders
FROM [dbo].[ORDERS]
WHERE YEAR([ORDER_DATE]) = 2008
GROUP BY [REP]
ORDER BY TotalOrders DESC;

